import express from "express";
import { upload } from "../middlewares/uploadMiddleware.js";

const router = express.Router();

/*
|--------------------------------------------------------------------------
| POST /api/v1/documents/upload
|--------------------------------------------------------------------------
| Upload one or more documents.
| Maximum Files : 10
| Maximum Size  : 10 MB per file
| Allowed Types : PDF, DOCX, DOC, TXT
|--------------------------------------------------------------------------
*/

router.post(
    "/upload",

    // "documents" must match the key name sent from the frontend FormData
    upload.array("documents", 10),

    (req, res) => {

        // If no file is uploaded
        if (!req.files || req.files.length === 0) {

            return res.status(400).json({
                success: false,
                message: "No files were uploaded."
            });

        }

        /*
        ---------------------------------------------------------------
        Prepare uploaded file information.
        Later this information will be passed to the PDF parser,
        chunking service and embedding service.
        ---------------------------------------------------------------
        */

        const uploadedFiles = req.files.map(file => ({

            // Original filename selected by the user
            originalName: file.originalname,

            // Unique filename generated by Multer
            filename: file.filename,

            // Complete file path on local storage
            path: file.path,

            // File size in bytes
            size: file.size,

            // MIME type
            mimeType: file.mimetype

        }));

        /*
        ---------------------------------------------------------------
        Response
        ---------------------------------------------------------------
        */

        return res.status(200).json({

            success: true,

            message: "Files uploaded successfully.",

            totalFiles: uploadedFiles.length,

            files: uploadedFiles

        });

    }

);

export default router;